<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>tomat</AssemblyName>
    <ApplicationIcon>tomat.ico</ApplicationIcon>
    <Product>tomat</Product>
    <Company>b1no</Company>
    <Authors>b1no</Authors>
	  <Publisher>b1no</Publisher>
    <Copyright>© 2026 b1no. All rights reserved</Copyright>
  	<AssemblyVersion>2.0.0</AssemblyVersion>
    <FileVersion>2.0.0</FileVersion>
  	<Version>2.0.0</Version>
    <InformationalVersion>Stable</InformationalVersion>
	  <RepositoryUrl>https://github.com/Storinob/tomat</RepositoryUrl>
  </PropertyGroup>
</Project>